[build]
  command = "npm run build:css"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://borderbug.netlify.app/*"
  to = "https://borderbug.com/:splat"
  status = 301
  force = true
